// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzlCmJmvc3jelUZSMN00NV4_a1UibeXtI',
    appId: '1:789658499799:web:dc4749ef1283618d868e92',
    messagingSenderId: '789658499799',
    projectId: 'tracking-6fc7c',
    authDomain: 'tracking-6fc7c.firebaseapp.com',
    storageBucket: 'tracking-6fc7c.firebasestorage.app',
    measurementId: 'G-PVPJXBT41M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs8HwUroBoLz3fl4kMQq-TeMhLg5okFn4',
    appId: '1:789658499799:android:416e2c41d416e92b868e92',
    messagingSenderId: '789658499799',
    projectId: 'tracking-6fc7c',
    storageBucket: 'tracking-6fc7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjSw6E-ajerPjf-TDWMvYTTKF6iVa9-Cw',
    appId: '1:789658499799:ios:ee14589519652c78868e92',
    messagingSenderId: '789658499799',
    projectId: 'tracking-6fc7c',
    storageBucket: 'tracking-6fc7c.firebasestorage.app',
    iosBundleId: 'com.example.tracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjSw6E-ajerPjf-TDWMvYTTKF6iVa9-Cw',
    appId: '1:789658499799:ios:ee14589519652c78868e92',
    messagingSenderId: '789658499799',
    projectId: 'tracking-6fc7c',
    storageBucket: 'tracking-6fc7c.firebasestorage.app',
    iosBundleId: 'com.example.tracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzlCmJmvc3jelUZSMN00NV4_a1UibeXtI',
    appId: '1:789658499799:web:f2f2ff75b2486a9e868e92',
    messagingSenderId: '789658499799',
    projectId: 'tracking-6fc7c',
    authDomain: 'tracking-6fc7c.firebaseapp.com',
    storageBucket: 'tracking-6fc7c.firebasestorage.app',
    measurementId: 'G-B895XQDBY1',
  );
}
